apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo:latest
    command:
    - mongod
    - --port
    - 27017
    - --dbpath
    - /data/db
    volumeMounts:
    - name: data
      mountPath: /data/db
  volumes:
  - name: data
    emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
data:
  init-mongo.js: |-
    db.process_engine.insert({
      "_id": ObjectId(),
      "cor_id": "correlation-123",
      "event_success": true,
      "image_name": "image-123.jpg",
      "creator_name": "John Doe",
      "s3_path": "s3://bucket/path/file.txt",
      "timestamp": new Date()
    })
